### ISSUE TITLE
bump apprise package version - slack markdown fix

### ISSUE THREAD

**Issue by pnadolny13** [AutoIDM/target-apprise#1]
Creating this issue to track bumping the apprise package version after the next release because it fixes https://github.com/caronc/apprise/issues/721 which caused Slack markdown not to render properly.

**Comment by visch** [comment]
Perfect as soon as caronc has a released version we can bump this!

**Comment by pnadolny13** [comment]
A new release was created yesterday https://github.com/caronc/apprise/releases/tag/v1.2.0
